### ISSUE TITLE
Can we implement more properties of BandedBlockBandedMatrix?

### ISSUE THREAD

**Issue by putianyi889** [JuliaMatrices/BlockBandedMatrices.jl#105]
We can construct a banded-block-banded matrix with

`BandedBlockBandedMatrix(Zeros(sum(rows),sum(cols)), rows,cols, (l,u), (λ,μ))`

but there is no straight method to get `rows` and `cols` from the matrix.

**Comment by dlfivefifty** [comment]
` blockaxes(A) `

**Comment by putianyi889** [comment]
```julia
julia> BlockBandedMatrices.blockaxes(S)
(Block{1,Int64}[Block(1), Block(2), Block(3), Block(4), Block(5), Block(6), Block(7)], Block{1,Int64}[Block(1), Block(2), Block(3), Block(4), Block(5), Block(6), Block(7)])
```
I get that these blocks denote the row and column blocking. How do I get sizes of them? They don't seem to have related property.

**Comment by dlfivefifty** [comment]
` blocklengths ` , though if you only need one then you can do ` length(blockaxes(A,1)[Block(k)])

**Comment by putianyi889** [comment]
https://github.com/JuliaArrays/BlockArrays.jl/pull/155
