### ISSUE TITLE
Yet another error in complex QR

### ISSUE THREAD

**Issue by jagot** [JuliaMatrices/BlockBandedMatrices.jl#35]
I realized that QR/QL factorizations still don't work with complex matrices, since the example I provided yesterday did not have any off-diagonal blocks, and hence the `apply_qr!` function, that's only implemented for the real case at the moment, was never run. I have a fix, and just want to put together a decent test.

**Comment by jagot** [comment]
This is the fix:
```julia
_apply_qr!(::AbstractColumnMajor, ::AbstractStridedLayout, ::AbstractStridedLayout, A::AbstractMatrix{T}, τ::AbstractVector{T}, B::AbstractVecOrMat{T}) where T<:BlasReal =
    LAPACK.ormqr!('L','T',A,τ,B)
_apply_qr!(::AbstractColumnMajor, ::AbstractStridedLayout, ::AbstractStridedLayout, A::AbstractMatrix{T}, τ::AbstractVector{T}, B::AbstractVecOrMat{T}) where T<:BlasComplex =
    LAPACK.ormqr!('L','C',A,τ,B)
```

Would you prefer having a ternary operator `T<:BlasReal ? 'T' : 'C'` instead of two methods?

**Comment by dlfivefifty** [comment]
Two methods is better since that’s how LinearAlgebra.jl does these things.
