### ISSUE TITLE
Precompilation failure in mybinder.org

### ISSUE THREAD

**Issue by ivborissov** [JuliaMatrices/BlockBandedMatrices.jl#45]
Hi,
`BlockBandedMatrices` package fails to precompile in [https://mybinder.org/](https://mybinder.org/) environment. @ChrisRackauckas  helped to upstream the original issue https://github.com/JuliaDiffEq/SparseDiffTools.jl/issues/69 .It can be reproduced by provisioning a simple mybinder notebook, 
https://mybinder.org/v2/gh/davidanthoff/bindertest/master?filepath=src%2Fmain.ipynb
and running
```
using Pkg; Pkg.add("BlockBandedMatrices")
using BlockBandedMatrices

Failed to precompile BlockBandedMatrices [ffab5731-97b5-5995-9138-79e8c1846df0] to /srv/julia/pkg/compiled/v1.1/BlockBandedMatrices/0zTvf.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] top-level scope at In[1]:2
```

This issue is not present with my local Julia. So it seems to be related only to the environments provisioned with mybinder.  
Also `BlockBandedMatrices v0.4.6` precompiles without errors in mybinder

**Comment by dlfivefifty** [comment]
can you try the following packages to see if they precompile:

FillArrays
MacroTools
LazyArrays
BandedMatrices
BlockArrays

**Comment by ivborissov** [comment]
All these packages precompile without errors except `BandedMatrices`. `using BandedMatrices` in mybinder results in `The kernel appears to have died` which is hard to debug. Can it be related to resource limits of `mybinder` environments?
Older versions of `BandedMatrices` (0.12.0) precompile without errors in mybinder

**Comment by dlfivefifty** [comment]
Yes that’s probably it: latest versions are hitting compiler inference bugs that cause significant memory usage at compile time. I’m closing this as there’s nothing that can be reasonably done.
