### ISSUE TITLE
Update constructor docs

### ISSUE THREAD

**Issue by cossio** [JuliaMatrices/BlockBandedMatrices.jl#65]
The docs suggest the following call signature (https://juliamatrices.github.io/BlockBandedMatrices.jl/latest/):

```
BlockBandedMatrix{T}(undef, (rows, cols), (l, u))
```

but this is incorrect. The correct signature is:

```
BlockBandedMatrix{T}(undef, rows, cols, (l, u))
```

Please update the docs.

**Comment by jagot** [comment]
Fixed in #79.
