### ISSUE TITLE
Inference issues due to changes in BandedMatrices.jl

### ISSUE THREAD

**Issue by rdeits** [JuliaMatrices/BlockBandedMatrices.jl#9]
The new `CONTAINER` type parameter in `BandedMatrix` has made some formerly-concrete fields now non-concrete. For example: 

```julia
struct BlockBandedSizes
    block_sizes::BlockSizes{2}
    block_starts::BandedMatrix{Int} # gives index where the blocks start
    block_strides::Vector{Int} # gives stride to next block for J-th column
end
```

that `BandedMatrix{Int}` is now actually a `BandedMatrix{Int, C} where C`, which is causing some inference and performance issues when working with views. 

We should either make `CONTAINER` also a type parameter of `BlockBandedSizes` or enforce a particular container type (presumably `Matrix{T}` as it was before). I'm not familiar enough with these packages yet to know which one to prefer. Any suggestions?

**Comment by dlfivefifty** [comment]
Nice catch, I don’t know how I missed that. I’ll hardcode ` Matrix{T} ` and retag. 

Allowing general backends (Think distributed arrays l) is in the pipeline for thIs package.

**Comment by rdeits** [comment]
Ok, sounds good. Thank you!

**Comment by dlfivefifty** [comment]
Do you have a good test for where the inference breaks, so I can add `@inferred` to the unit tests?

**Comment by rdeits** [comment]
Sure, how about: 

```julia
s = BlockBandedMatrices.BlockBandedSizes([1, 2], [1, 2], 0, 0)
f(s) = s.block_starts.data
@inferred(f(s))
```
